- name: Add docker gpg key
  become: true
  apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg
  tags:
    - docker

- name: Add docker repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  tags:
    - docker

- name: Update repository index
  become: true
  apt:
    upgrade: true
    update_cache: true
  tags:
    - docker

- name: Install docker
  become: true
  package:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  tags:
    - docker

- name: Start service docker, if not started
  become: true
  service:
    name: docker
    state: started
  tags:
    - docker

- name: Enable service docker, and not touch the state
  become: true
  service:
    name: docker
    enabled: true
  tags:
    - docker
